# db/seeds/countries_es.rb

puts "🌍 Cargando países (nombre en español, ISO, prefijo telefónico)..."

countries = [
  { name: "Afganistán", iso_code: "AF", phone_prefix: "+93" },
  { name: "Albania", iso_code: "AL", phone_prefix: "+355" },
  { name: "Alemania", iso_code: "DE", phone_prefix: "+49" },
  { name: "Andorra", iso_code: "AD", phone_prefix: "+376" },
  { name: "Angola", iso_code: "AO", phone_prefix: "+244" },
  { name: "Argentina", iso_code: "AR", phone_prefix: "+54" },
  { name: "Armenia", iso_code: "AM", phone_prefix: "+374" },
  { name: "Australia", iso_code: "AU", phone_prefix: "+61" },
  { name: "Austria", iso_code: "AT", phone_prefix: "+43" },
  { name: "Azerbaiyán", iso_code: "AZ", phone_prefix: "+994" },
  { name: "Bahamas", iso_code: "BS", phone_prefix: "+1-242" },
  { name: "Bahréin", iso_code: "BH", phone_prefix: "+973" },
  { name: "Bangladés", iso_code: "BD", phone_prefix: "+880" },
  { name: "Barbados", iso_code: "BB", phone_prefix: "+1-246" },
  { name: "Bélgica", iso_code: "BE", phone_prefix: "+32" },
  { name: "Belice", iso_code: "BZ", phone_prefix: "+501" },
  { name: "Benín", iso_code: "BJ", phone_prefix: "+229" },
  { name: "Bhután", iso_code: "BT", phone_prefix: "+975" },
  { name: "Bolivia", iso_code: "BO", phone_prefix: "+591" },
  { name: "Bosnia y Herzegovina", iso_code: "BA", phone_prefix: "+387" },
  { name: "Botsuana", iso_code: "BW", phone_prefix: "+267" },
  { name: "Brasil", iso_code: "BR", phone_prefix: "+55" },
  { name: "Brunéi", iso_code: "BN", phone_prefix: "+673" },
  { name: "Bulgaria", iso_code: "BG", phone_prefix: "+359" },
  { name: "Burkina Faso", iso_code: "BF", phone_prefix: "+226" },
  { name: "Burundi", iso_code: "BI", phone_prefix: "+257" },
  { name: "Cabo Verde", iso_code: "CV", phone_prefix: "+238" },
  { name: "Camboya", iso_code: "KH", phone_prefix: "+855" },
  { name: "Camerún", iso_code: "CM", phone_prefix: "+237" },
  { name: "Canadá", iso_code: "CA", phone_prefix: "+1" },
  { name: "Chad", iso_code: "TD", phone_prefix: "+235" },
  { name: "Chile", iso_code: "CL", phone_prefix: "+56" },
  { name: "China", iso_code: "CN", phone_prefix: "+86" },
  { name: "Chipre", iso_code: "CY", phone_prefix: "+357" },
  { name: "Colombia", iso_code: "CO", phone_prefix: "+57" },
  { name: "Comoras", iso_code: "KM", phone_prefix: "+269" },
  { name: "Costa Rica", iso_code: "CR", phone_prefix: "+506" },
  { name: "Croacia", iso_code: "HR", phone_prefix: "+385" },
  { name: "Cuba", iso_code: "CU", phone_prefix: "+53" },
  { name: "Dinamarca", iso_code: "DK", phone_prefix: "+45" },
  { name: "Djibouti", iso_code: "DJ", phone_prefix: "+253" },
  { name: "Dominica", iso_code: "DM", phone_prefix: "+1-767" },
  { name: "Ecuador", iso_code: "EC", phone_prefix: "+593" },
  { name: "Egipto", iso_code: "EG", phone_prefix: "+20" },
  { name: "El Salvador", iso_code: "SV", phone_prefix: "+503" },
  { name: "Eritrea", iso_code: "ER", phone_prefix: "+291" },
  { name: "Eslovaquia", iso_code: "SK", phone_prefix: "+421" },
  { name: "Eslovenia", iso_code: "SI", phone_prefix: "+386" },
  { name: "España", iso_code: "ES", phone_prefix: "+34" },
  { name: "Estados Unidos", iso_code: "US", phone_prefix: "+1" },
  { name: "Estonia", iso_code: "EE", phone_prefix: "+372" },
  { name: "Etiopía", iso_code: "ET", phone_prefix: "+251" },
  { name: "Filipinas", iso_code: "PH", phone_prefix: "+63" },
  { name: "Finlandia", iso_code: "FI", phone_prefix: "+358" },
  { name: "Francia", iso_code: "FR", phone_prefix: "+33" },
  { name: "Gabón", iso_code: "GA", phone_prefix: "+241" },
  { name: "Gambia", iso_code: "GM", phone_prefix: "+220" },
  { name: "Georgia", iso_code: "GE", phone_prefix: "+995" },
  { name: "Ghana", iso_code: "GH", phone_prefix: "+233" },
  { name: "Granada", iso_code: "GD", phone_prefix: "+1-473" },
  { name: "Grecia", iso_code: "GR", phone_prefix: "+30" },
  { name: "Guatemala", iso_code: "GT", phone_prefix: "+502" },
  { name: "Guinea", iso_code: "GN", phone_prefix: "+224" },
  { name: "Guinea-Bisáu", iso_code: "GW", phone_prefix: "+245" },
  { name: "Guyana", iso_code: "GY", phone_prefix: "+592" },
  { name: "Haití", iso_code: "HT", phone_prefix: "+509" },
  { name: "Honduras", iso_code: "HN", phone_prefix: "+504" },
  { name: "Hungría", iso_code: "HU", phone_prefix: "+36" },
  { name: "India", iso_code: "IN", phone_prefix: "+91" },
  { name: "Indonesia", iso_code: "ID", phone_prefix: "+62" },
  { name: "Irán", iso_code: "IR", phone_prefix: "+98" },
  { name: "Iraq", iso_code: "IQ", phone_prefix: "+964" },
  { name: "Irlanda", iso_code: "IE", phone_prefix: "+353" },
  { name: "Islandia", iso_code: "IS", phone_prefix: "+354" },
  { name: "Islas Caimán", iso_code: "KY", phone_prefix: "+1-345" },
  { name: "Islas Cook", iso_code: "CK", phone_prefix: "+682" },
  { name: "Israel", iso_code: "IL", phone_prefix: "+972" },
  { name: "Italia", iso_code: "IT", phone_prefix: "+39" },
  { name: "Jamaica", iso_code: "JM", phone_prefix: "+1-876" },
  { name: "Japón", iso_code: "JP", phone_prefix: "+81" },
  { name: "Jordania", iso_code: "JO", phone_prefix: "+962" },
  { name: "Kazajistán", iso_code: "KZ", phone_prefix: "+7" },
  { name: "Kenia", iso_code: "KE", phone_prefix: "+254" },
  { name: "Kirguistán", iso_code: "KG", phone_prefix: "+996" },
  { name: "Kiribati", iso_code: "KI", phone_prefix: "+686" },
  { name: "Kosovo", iso_code: "XK", phone_prefix: "+383" },
  { name: "Kuwait", iso_code: "KW", phone_prefix: "+965" },
  { name: "Laos", iso_code: "LA", phone_prefix: "+856" },
  { name: "Letonia", iso_code: "LV", phone_prefix: "+371" },
  { name: "Líbano", iso_code: "LB", phone_prefix: "+961" },
  { name: "Liberia", iso_code: "LR", phone_prefix: "+231" },
  { name: "Libia", iso_code: "LY", phone_prefix: "+218" },
  { name: "Liechtenstein", iso_code: "LI", phone_prefix: "+423" },
  { name: "Lituania", iso_code: "LT", phone_prefix: "+370" },
  { name: "Luxemburgo", iso_code: "LU", phone_prefix: "+352" },
  { name: "Macedonia del Norte", iso_code: "MK", phone_prefix: "+389" },
  { name: "Madagascar", iso_code: "MG", phone_prefix: "+261" },
  { name: "Malasia", iso_code: "MY", phone_prefix: "+60" },
  { name: "Malaui", iso_code: "MW", phone_prefix: "+265" },
  { name: "Maldivas", iso_code: "MV", phone_prefix: "+960" },
  { name: "Malí", iso_code: "ML", phone_prefix: "+223" },
  { name: "Malta", iso_code: "MT", phone_prefix: "+356" },
  { name: "Marruecos", iso_code: "MA", phone_prefix: "+212" },
  { name: "Mauricio", iso_code: "MU", phone_prefix: "+230" },
  { name: "México", iso_code: "MX", phone_prefix: "+52" },
  { name: "Micronesia", iso_code: "FM", phone_prefix: "+691" },
  { name: "Moldavia", iso_code: "MD", phone_prefix: "+373" },
  { name: "Mónaco", iso_code: "MC", phone_prefix: "+377" },
  { name: "Mongolia", iso_code: "MN", phone_prefix: "+976" },
  { name: "Montenegro", iso_code: "ME", phone_prefix: "+382" },
  { name: "Mozambique", iso_code: "MZ", phone_prefix: "+258" },
  { name: "Namibia", iso_code: "NA", phone_prefix: "+264" },
  { name: "Nauru", iso_code: "NR", phone_prefix: "+674" },
  { name: "Nepal", iso_code: "NP", phone_prefix: "+977" },
  { name: "Nicaragua", iso_code: "NI", phone_prefix: "+505" },
  { name: "Níger", iso_code: "NE", phone_prefix: "+227" },
  { name: "Nigeria", iso_code: "NG", phone_prefix: "+234" },
  { name: "Noruega", iso_code: "NO", phone_prefix: "+47" },
  { name: "Nueva Zelanda", iso_code: "NZ", phone_prefix: "+64" },
  { name: "Omán", iso_code: "OM", phone_prefix: "+968" },
  { name: "Pakistán", iso_code: "PK", phone_prefix: "+92" },
  { name: "Palaos", iso_code: "PW", phone_prefix: "+680" },
  { name: "Panamá", iso_code: "PA", phone_prefix: "+507" },
  { name: "Papúa Nueva Guinea", iso_code: "PG", phone_prefix: "+675" },
  { name: "Paraguay", iso_code: "PY", phone_prefix: "+595" },
  { name: "Perú", iso_code: "PE", phone_prefix: "+51" },
  { name: "Polonia", iso_code: "PL", phone_prefix: "+48" },
  { name: "Portugal", iso_code: "PT", phone_prefix: "+351" },
  { name: "República Checa", iso_code: "CZ", phone_prefix: "+420" },
  { name: "República Dominicana", iso_code: "DO", phone_prefix: "+1-849" },
  { name: "Rumanía", iso_code: "RO", phone_prefix: "+40" },
  { name: "Rusia", iso_code: "RU", phone_prefix: "+7" },
  { name: "Sudáfrica", iso_code: "ZA", phone_prefix: "+27" },
  { name: "Suecia", iso_code: "SE", phone_prefix: "+46" },
  { name: "Suiza", iso_code: "CH", phone_prefix: "+41" },
  { name: "Tailandia", iso_code: "TH", phone_prefix: "+66" },
  { name: "Turquía", iso_code: "TR", phone_prefix: "+90" },
  { name: "Ucrania", iso_code: "UA", phone_prefix: "+380" },
  { name: "Uganda", iso_code: "UG", phone_prefix: "+256" },
  { name: "Uruguay", iso_code: "UY", phone_prefix: "+598" },
  { name: "Uzbekistán", iso_code: "UZ", phone_prefix: "+998" },
  { name: "Venezuela", iso_code: "VE", phone_prefix: "+58" },
  { name: "Vietnam", iso_code: "VN", phone_prefix: "+84" },
  { name: "Zambia", iso_code: "ZM", phone_prefix: "+260" },
  { name: "Zimbabue", iso_code: "ZW", phone_prefix: "+263" }
]

countries.sort_by { |c| c[:name] }.each do |attrs|
  Saas::Country.find_or_create_by!(iso_code: attrs[:iso_code]) do |c|
    c.name = attrs[:name]
    c.phone_prefix = attrs[:phone_prefix]
  end
end

puts "✅ Países cargados: #{Saas::Country.count}"
